<!DOCTYPE html>
<html lang="bn">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Shope Zone BD - ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛</title>

  <!-- SEO Meta Tags -->
  <meta name="description" content="Shope Zone BD ржерзЗржХрзЗ ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛ ржХрж┐ржирзБржи тАФ рж╕рж╣ржЬ ржЕрж░рзНржбрж╛рж░, ржкрзЯрзЗржирзНржЯ рж╕рж┐рж╕рзНржЯрзЗржо ржУ ржлрзНрж░рж┐ ржЧрж┐ржлржЯ!" />
  <meta name="keywords" content="ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛, Shope Zone BD, рж░рж╛ржирзНржирж╛рж░ ржЪрзБрж▓рж╛, ржЕржирж▓рж╛ржЗржи ржЪрзБрж▓рж╛ ржмрж┐ржХрзНрж░рж┐, WhatsApp ржЕрж░рзНржбрж╛рж░, ржмрж╛ржВрж▓рж╛ржжрзЗрж╢ ржЕржирж▓рж╛ржЗржи ржорж╛рж░рзНржХрзЗржЯ" />
  <meta name="author" content="Shope Zone BD" />
  <meta property="og:title" content="Shope Zone BD - ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛" />
  <meta property="og:description" content="ржлрзНрж░рж┐ ржЧрж┐ржлржЯ ржУ ржкрзЯрзЗржирзНржЯ рж╕рж┐рж╕рзНржЯрзЗржо рж╕рж╣ ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛ ржХрж┐ржирзБржи" />
  <meta property="og:image" content="https://i.imgur.com/SZJ3YpD.jpg" />
  <meta property="og:url" content="https://shope-zone-bd.vercel.app" />
  <meta name="robots" content="index, follow" />

  <!-- Preload main product image -->
  <link rel="preload" as="image" href="https://i.imgur.com/SZJ3YpD.jpg" />

  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #fefefe;
      margin: 0; padding: 0;
    }
    header {
      background-color: #e63946;
      color: white;
      text-align: center;
      padding: 1.2rem 0;
    }
    .container {
      max-width: 900px;
      margin: auto;
      padding: 1rem;
      background-color: #fff;
    }
    h2 {
      color: #1d3557;
      margin-top: 20px;
    }
    .product {
      border: 1px solid #ddd;
      padding: 1rem;
      border-radius: 10px;
      margin-bottom: 1.5rem;
      box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .product img {
      width: 100%;
      max-height: 300px;
      object-fit: cover;
      border-radius: 10px;
    }
    .btn {
      display: inline-block;
      background-color: #1d3557;
      color: white;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      margin-top: 10px;
      transition: background 0.3s;
    }
    .btn:hover {
      background-color: #457b9d;
    }
    .note {
      background: #f1faee;
      padding: 15px;
      border-left: 5px solid #457b9d;
      margin-top: 20px;
      border-radius: 6px;
    }
    footer {
      text-align: center;
      background-color: #f8f8f8;
      padding: 1rem;
      margin-top: 2rem;
      font-size: 14px;
    }
    @media (max-width: 600px) {
      .btn {
        width: 100%;
        text-align: center;
      }
    }
  </style>
</head>
<body>
  <header>
    <h1>Shope Zone BD</h1>
    <p>ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛, ржХрзНрж▓ржерж┐ржВ, ржЬрзБржпрж╝рзЗрж▓рж╛рж░рж┐ ржПржмржВ ржЖрж░ржУ ржЕржирзЗржХ ржХрж┐ржЫрзБ</p>
  </header>

  <div class="container">
    <h2>ЁЯФе ржЬржиржкрзНрж░рж┐рзЯ ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛</h2>

    <div class="product">
      <img src="https://i.imgur.com/SZJ3YpD.jpg" alt="рж╕рзНржЯрзЗржЗржирж▓рзЗрж╕ рж╕рзНржЯрж┐рж▓ ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛ - рзи ржЪрзБрж▓рж╛, Shope Zone BD" loading="lazy" />
      <h3>рж╕рзНржЯрзЗржЗржирж▓рзЗрж╕ рж╕рзНржЯрж┐рж▓ ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛ - рзи ржЪрзБрж▓рж╛</h3>
      <p>ржорзВрж▓рзНржп: рз│рзи,рзорзжрзж<br>ЁЯФз ржлрзНрж░рж┐ ржЗржирж╕рзНржЯрж▓рзЗрж╢ржи: тЭМ</p>
      <a class="btn" href="https://wa.me/8801616271469?text=ржЖржорж┐ ржЧрзНржпрж╛рж╕ ржЪрзБрж▓рж╛ ржЕрж░рзНржбрж╛рж░ ржХрж░рждрзЗ ржЪрж╛ржЗ - рзирзорзжрзж ржЯрж╛ржХрж╛" target="_blank" rel="noopener noreferrer">WhatsApp ржП ржЕрж░рзНржбрж╛рж░ ржХрж░рзБржи</a>
    </div>

    <div class="note">
      ЁЯОп ржкрзНрж░рждрж┐ ржЕрж░рзНржбрж╛рж░рзЗ ржЖржкржирж┐ ржкрж╛ржмрзЗржи <strong>рззрзжрзж ржкржпрж╝рзЗржирзНржЯ</strong><br>
      ЁЯФД рзйрзжрзж ржкржпрж╝рзЗржирзНржЯрзЗ рзи% ржЫрж╛ржбрж╝<br>
      ЁЯФД рзмрзжрзж ржкржпрж╝рзЗржирзНржЯрзЗ рзй% ржЫрж╛ржбрж╝<br>
      ЁЯФД рзпрзжрзж ржкржпрж╝рзЗржирзНржЯрзЗ рзк% ржЫрж╛ржбрж╝<br>
      ЁЯОБ рзлрзжрзж ржкржпрж╝рзЗржирзНржЯрзЗ ржкрж╛ржмрзЗржи ржлрзНрж░рж┐ ржЧрж┐ржлржЯ!
    </div>
  </div>

  <footer>
    ЁЯУЮ WhatsApp: 01616271469 | ЁЯУз Email: armanfaruq00000@gmail.com
  </footer>
</body>
</html>
